name: SauceDemo Cypress CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          install: false
          command: npx cypress run

      - name: Upload Mochawesome HTML Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-test-report
          path: cypress/reports
